name: Build

on: 'push'

jobs:
  build_files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 23
      - run: npm install
      - run: npm run package
      - run: npm run make
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: archive-${{ matrix.os }}
          if-no-files-found: ignore
          path: |
            out/make/**/*.zip
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.exe
            out/make/**/*.nupkg
